wipe = true
pkgname = "models"
output = "internal/models"
add_soft_deletes = true

[crdb]
dbname = "serverservice_test"
host = "localhost"
port = 26257
user = "root"
sslmode = "disable"
blacklist = ["goose_db_version"]
